/** Ülke telefon kodları (ülke adı + kod), iPhone tarzı seçicide kullanılır. */
export const PHONE_COUNTRY_CODES: { code: string; name: string }[] = [
  { code: '90', name: 'Türkiye' },
  { code: '49', name: 'Almanya' },
  { code: '43', name: 'Avusturya' },
  { code: '32', name: 'Belçika' },
  { code: '359', name: 'Bulgaristan' },
  { code: '45', name: 'Danimarka' },
  { code: '358', name: 'Finlandiya' },
  { code: '33', name: 'Fransa' },
  { code: '31', name: 'Hollanda' },
  { code: '353', name: 'İrlanda' },
  { code: '34', name: 'İspanya' },
  { code: '46', name: 'İsveç' },
  { code: '41', name: 'İsviçre' },
  { code: '39', name: 'İtalya' },
  { code: '44', name: 'İngiltere' },
  { code: '30', name: 'Yunanistan' },
  { code: '48', name: 'Polonya' },
  { code: '351', name: 'Portekiz' },
  { code: '40', name: 'Romanya' },
  { code: '7', name: 'Rusya' },
  { code: '420', name: 'Çekya' },
  { code: '36', name: 'Macaristan' },
  { code: '380', name: 'Ukrayna' },
  { code: '1', name: 'ABD / Kanada' },
  { code: '971', name: 'BAE' },
  { code: '966', name: 'Suudi Arabistan' },
  { code: '972', name: 'İsrail' },
  { code: '20', name: 'Mısır' },
  { code: '98', name: 'İran' },
  { code: '964', name: 'Irak' },
  { code: '962', name: 'Ürdün' },
  { code: '961', name: 'Lübnan' },
  { code: '963', name: 'Suriye' },
  { code: '994', name: 'Azerbaycan' },
  { code: '995', name: 'Gürcistan' },
  { code: '374', name: 'Ermenistan' },
  { code: '993', name: 'Türkmenistan' },
  { code: '998', name: 'Özbekistan' },
  { code: '996', name: 'Kırgızistan' },
  { code: '992', name: 'Tacikistan' },
  { code: '62', name: 'Endonezya' },
  { code: '91', name: 'Hindistan' },
  { code: '86', name: 'Çin' },
  { code: '81', name: 'Japonya' },
  { code: '82', name: 'Güney Kore' },
  { code: '61', name: 'Avustralya' },
  { code: '55', name: 'Brezilya' },
  { code: '52', name: 'Meksika' },
  { code: '27', name: 'Güney Afrika' },
  { code: '234', name: 'Nijerya' },
  { code: '212', name: 'Fas' },
  { code: '213', name: 'Cezayir' },
  { code: '216', name: 'Tunus' },
  { code: '90', name: 'Kıbrıs (KKTC)' },
]
